/*
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UsersPost - Creates a new user.
func UsersPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersUserIdGet - Returns a user by ID.
func UsersUserIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
