version: '3'
services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - .:/app
    ports:
    - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080